name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker images
      run: |
        docker build -t your-dockerhub-username/app-frontend:latest -f Dockerfile.frontend .
        docker build -t your-dockerhub-username/app-backend:latest -f Dockerfile .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push your-dockerhub-username/app-frontend:latest
        docker push your-dockerhub-username/app-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment-frontend.yaml
        kubectl apply -f service-frontend.yaml
        kubectl apply -f deployment-backend.yaml
        kubectl apply -f service-backend.yaml